version: '3'
services:
  mongodb:
    restart: always
    image: mongo    
    container_name: jwt_example_db
    environment:    
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"    
    ports: 
      - 17017:27017
    networks: 
      - backbone
   
  server-code: 
    restart: always
    container_name: jwt_example_api
    build:
      context: .
      dockerfile: apidockerfile
    depends_on:
     - mongodb     
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: jwt_example_db:27017      
    networks:
        - backbone   

  ui-code: 
    restart: always
    container_name: jwt_example_angular
    build:
      context: src\main\web-angular
      dockerfile: uidockerfile
    links:
       - server-code
    depends_on:
     - server-code
    expose:
      - "4200"
    ports:
      - 4200:80
    networks:
        - backbone       
networks:
  backbone:
   driver: bridge   
        
        